Add retry handling
extreal-dev/Extreal.Integration.Multiplay pull request #16
Opened 2023-02-06 14:58 UTC by kiyohome

# 何の変更を加えましたか？

Commitsを見てください。

# 何を確認しましたか?

## 実装

- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
- [x] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [x] 全ての自動テストが成功することを確認しました
- [x] テストカバレッジが100%になることを確認しました
- [x] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [x] GuideのReleaseページに変更内容が追加されることを確認しました
- [x] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
  - https://github.com/extreal-dev/Extreal.Guide/pull/39
- [x] GuideのLearningページに変更が反映されることを確認しました
  - 反映予定なし
- [x] Sample Applicationに変更が反映されることを確認しました
  - 別途対応予定

# レビュアーへのメッセージ

- Holidayには別PBIで反映します。

2023-02-08 02:58 UTC, sus-taguchi-t requested changes

2023-02-08 02:58 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            connectRetryHandler.OnRetrying.Subscribe(onConnectRetrying.OnNext).AddTo(connectRetryHandlerDisposables);
```csharp
OnConnectRetrying = connectRetryHandler.OnRetrying;
OnConnectRetried = connectRetryHandler.OnRetried;
```

`OnConnectRetrying` および `OnConnectRetried` の宣言を `{ get; private set; }` にして上記のようにすれば `connectRetryHandlerDisposables`, `onConnectRetrying` および `onConnectRetried`がなくても実装できると思ったのですがいかがでしょう。

2023-02-08 02:58 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            Func<UniTask<bool>> connectAsync = async () =>
私の環境では `IDE0039` の「ローカル関数を使用します」という静的解析が警告を発しています。
これを適用するとここの変数宣言の 1 行が `async UniTask<bool> connectAsync()` というローカル関数宣言に変わり、右辺の最後にあったセミコロンがなくなります。

2023-02-08 02:58 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            return await connectRetryHandler.HandleAsync();
ここの `await` を削除してこの関数（`ConnectAsync`）の宣言から `async` を削除しても同等な挙動になり、その上で少しコードが簡素化されるので良いかもしれません。

2023-02-14 12:44 UTC, kiyohome commented on Runtime/NgoClient.cs
> +            connectRetryHandler.OnRetrying.Subscribe(onConnectRetrying.OnNext).AddTo(connectRetryHandlerDisposables);
I think that's good!
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/16/commits/8df926a1972fcc28ff8a6606579bc187f8ad57dd

2023-02-14 12:48 UTC, kiyohome commented on Runtime/NgoClient.cs
> +            Func<UniTask<bool>> connectAsync = async () =>
Disable IDE0039
https://github.com/extreal-dev/Extreal.Dev/commit/8bf754265c39cc61326241078723d8eea87ed383

2023-02-14 14:12 UTC, kiyohome commented on Runtime/NgoClient.cs
> +            return await connectRetryHandler.HandleAsync();
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/16/commits/8bc3be881e8f6f5a22f2d482e4d826dbf5a75470

2023-02-22 07:42 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            connectRetryHandler.OnRetrying.Subscribe(onConnectRetrying.OnNext).AddTo(connectRetryHandlerDisposables);
確かにその通りです。
ありがとうございます！

2023-02-22 07:43 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            Func<UniTask<bool>> connectAsync = async () =>
確認しました！

2023-02-22 07:44 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            return await connectRetryHandler.HandleAsync();
確認しました！

2023-02-27 06:40 UTC, sus-taguchi-t requested changes

2023-02-27 06:40 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        /// Arg: Final results of retry. True for success, false for failure.
results -> result

2023-02-27 23:53 UTC, kiyohome commented on Runtime/NgoClient.cs
> +        /// Arg: Final results of retry. True for success, false for failure.
Fixed!
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/16/commits/4c5942568f3d434c723e67c6a162937119ccbb94

2023-02-28 06:47 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        /// Arg: Final results of retry. True for success, false for failure.
確認しました！

2023-02-28 06:47 UTC, sus-taguchi-t approved these changes

2023-02-28 06:47 UTC, merged