FW利用者がMultiplayを使えるようにする
extreal-dev/Extreal.Integration.Multiplay pull request #2
Opened 2022-10-31 05:03 UTC by sus-taguchi-t

close #1 

# Describe Your Changes (なんの変更を加えましたか?)

- [x] フォーマッタを導入した
- [x] 静的解析を導入した
- [ ] Multiplayのテストを作成した
- [x] Multiplayのライブラリを作成した
- [ ] C# ドキュメントを作成した

# What did you verify? (何を確認しましたか?)

- [ ] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [ ] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [ ] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [ ] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [ ] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

- [ ] ガイドに要件と使い方が書かれていますか？
- [ ] ガイドに対応するプロダクションコードと自動テストコードが作成されていますか？
- [ ] コードは読みやすいですか？
- [ ] 他に必要なテスト項目はありますか？

2022-11-09 08:54 UTC, sus-taguchi-t commented on Runtime/Extreal.Integration.Multiplay.NGO.asmdef
> +        "Extreal.Framework.Analyzer"
merge の前に `Extreal.Framework.Analyzer` を削除する。

2022-11-10 13:28 UTC, kiyohome requested changes

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoClient.cs
> +#pragma warning disable IDE0016
`#pragma warning disable IDE0016` を外しても指摘が出なかったのですがRiderだからですかね？

throw式とthrowステートメントの統一の話しであれば、どちらかに決めてeditorconfigに入れてはダメですかね？
できるだけ#paragmaを入れたくない思いがあります。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoClient.cs
> +            if (networkTransportInitializer is null)
`==null`と`is null`があるんですが`==null`だとダメでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/UnityTransportInitializer.cs
> +            if (networkTransport is UnityTransport unityTransport)
実装クラスの処理はこのIF文の内容だけになるようにしたいです。
- NetworkTransportが処理対象か？
- アドレス、ポート、リッスンアドレスの設定

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/ConnectionParameter.cs
> +    public class ConnectionParameter
ConnectionConfigとして1つのクラスにしたらダメでしょうか？
Parameter＞Config、Dataと階層にしている理由がよく分からなかったです。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/IConnectionData.cs
> +    public interface IConnectionData
このインタフェースの必要性が分からないです。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/INetworkTransportInitializer.cs
> +        void Initialize(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
根本的なところを確認させてください。
これが必要なのはNetworkManagerとNetworkTransportをプレハブにして、複数の接続先に対応させるためでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/INgoServer.cs
> +        IObservable<ulong> OnClientConnected { get; }
ulongの説明をドキュメンテーションコメントに書けないでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +        private Action<ConnectionApprovalRequest, ConnectionApprovalResponse> connectionApprovalCallback;
```
Field 'connectionApprovalCallback' is assigned but its value is never used
```
と出ています。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +#pragma warning disable IDE0016
これもできれば無くしたいです。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +                throw new InvalidOperationException("Unable to reject client because the server is not running");
rejct　→　removeでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +                    Logger.LogWarn($"Unable to reject client with client id {clientId} because it does not exist");
rejct　→　removeでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +        public bool RemoveClient(ulong clientId, string message)
質問です。
messageは何に使うものでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +            if (clientIds.Except(networkManager.ConnectedClientsIds).Count() != 0)
どのような場合に存在しないクライアントが発生するのでしょうか？
存在するクライアントにだけでもメッセージ送信しなくてアプリは困らないでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
Helperにしますか？Utilsではないでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
Spawnが動詞だとすると命名が変な感じがします。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            => SpawnInternal(0, prefab, position, rotation, parent, worldPositionStays, SpawnType.ServerOwnership);
質問です。0に固定でよいものでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +        public static GameObject SpawnAsPlayerObject
SpawnWithとSpawnAsがあるんですが異なるものでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn($"Null is accepted as {nameof(prefab)}");
実装不備ではないでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn("GameObject without NetworkObject cannot be spawned");
こちらも実装不備ではないでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +#pragma warning disable CC0120
できるだけpragmaを外したいです。

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            if (!TryCreateInstance(prefab, position, rotation, parent, worldPositionStays, out var instance))
できればoutパラメータは使いたくないですがいかがでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                Object.Destroy(instance);
instanceを作ったスコープと異なる場所でDestroyしていてややこしく感じましたが、そんなことはないでしょうか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +        public static GameObject SpawnAsPlayerObject
NetworkManagerに合わせた感じですかね？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/INgoSpawnObserver.cs
> +        IObservable<NetworkObject[]> OnSpawnedAsObservable { get; }
AsObservableを付けてる理由はありますか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/INgoSpawnObserver.cs
> +
書くとこないのでここに書きます。
CoreとSpawningを分けている理由はありますか？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
各Spawnメソッドはどこで呼び出す想定でしょうか？
サーバー？クライアント？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnObserver.cs
> +    public class NgoSpawnObserver : INgoSpawnObserver
こちらもどこから呼び出す想定でしょうか？
サーバー？クライアント？

2022-11-10 13:28 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnObserver.cs
> +            Clear();
StartとClearの関係がよく分からないです。

2022-11-11 01:46 UTC, kiyohome commented on Runtime/Core/NgoClient.cs
> +#pragma warning disable IDE0016
IDE0016は外しましょう。
Unityの管理しているオブジェクトのnull判定（is、??、?.など）は誤判定の可能性があるため。

2022-11-11 01:46 UTC, kiyohome commented on Runtime/Core/NgoClient.cs
> +            if (networkTransportInitializer is null)
==に倒しましょう。

2022-11-11 04:12 UTC, sus-taguchi-t commented on Runtime/Core/NgoClient.cs
> +#pragma warning disable IDE0016
分かりました。
修正します。

2022-11-11 04:12 UTC, sus-taguchi-t commented on Runtime/Core/NgoClient.cs
> +            if (networkTransportInitializer is null)
分かりました。
修正します。

2022-11-11 04:12 UTC, sus-taguchi-t commented on Runtime/Core/UnityTransportInitializer.cs
> +            if (networkTransport is UnityTransport unityTransport)
分かりました。
修正します。

2022-11-11 04:12 UTC, sus-taguchi-t commented on Runtime/Core/ConnectionParameter.cs
> +    public class ConnectionParameter
Config に集約させます。

2022-11-11 04:14 UTC, sus-taguchi-t commented on Runtime/Core/IConnectionData.cs
> +    public interface IConnectionData
シリアライズの処理をユーザが定義したいときに使用することを想定していました。
ライブラリの外でやれば良い話なのでこれはなくして `ConnectionParameter` の中では `data[]` の値を保持するだけにします

2022-11-11 07:53 UTC, sus-taguchi-t commented on Runtime/Spawning/INgoSpawnObserver.cs
> +        IObservable<NetworkObject[]> OnSpawnedAsObservable { get; }
特にありません。
削除します。

2022-11-11 07:54 UTC, sus-taguchi-t commented on Runtime/Spawning/INgoSpawnObserver.cs
> +
`Core` は必須、`Spawning` は任意のイメージでした。
分割をなくします。

2022-11-11 07:55 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
`Spawn` はサーバでしか呼べません。
`NgoServer` 内に処理を移します。

2022-11-11 07:55 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnObserver.cs
> +    public class NgoSpawnObserver : INgoSpawnObserver
どちらからでも呼び出すことが可能です。
ただ `Netcode` の思想と離れる気がする、かつ、処理が重くなるのでこれは削除します。

2022-11-11 07:56 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnObserver.cs
> +            Clear();
`Netcode` の思想と離れる気がする、かつ、処理が重くなるので `NgoSpawnObserver` は削除します。

2022-11-11 07:57 UTC, sus-taguchi-t commented on Runtime/Core/INetworkTransportInitializer.cs
> +        void Initialize(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
はい。

2022-11-11 07:57 UTC, sus-taguchi-t commented on Runtime/Core/INgoServer.cs
> +        IObservable<ulong> OnClientConnected { get; }
書きます。

2022-11-11 07:58 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +        private Action<ConnectionApprovalRequest, ConnectionApprovalResponse> connectionApprovalCallback;
私用しなくてよい書き方にしてあるので削除します。

2022-11-11 07:58 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +#pragma warning disable IDE0016
なくします。

2022-11-11 07:59 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +                throw new InvalidOperationException("Unable to reject client because the server is not running");
すみません。修正忘れていました。

2022-11-11 07:59 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +                    Logger.LogWarn($"Unable to reject client with client id {clientId} because it does not exist");
すみません。修正忘れていました。

2022-11-11 07:59 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +        public bool RemoveClient(ulong clientId, string message)
特に使用例が思いつきません。
削除します。

2022-11-11 08:00 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +            if (clientIds.Except(networkManager.ConnectedClientsIds).Count() != 0)
存在しないクライアントはデバッグログを出しておいて、それ以外の存在するクライアントにはメッセージを送信するように変更します。

2022-11-11 08:00 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
`NgoServer` に処理を移すので、このスクリプトは削除します。

2022-11-11 08:01 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
`NgoServer` に処理を移すので、このスクリプトは削除します。

2022-11-11 08:01 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            => SpawnInternal(0, prefab, position, rotation, parent, worldPositionStays, SpawnType.ServerOwnership);
実際には使用していない引数なので固定して良いものです。
隠ぺいできるようにオプション引数に変更します。

2022-11-11 08:02 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +        public static GameObject SpawnAsPlayerObject
はい。

2022-11-11 08:02 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn($"Null is accepted as {nameof(prefab)}");
実装不備です。
エクセプションを投げさせます。

2022-11-11 08:02 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn("GameObject without NetworkObject cannot be spawned");
実装不備です。
エクセプションを投げさせます。

2022-11-11 08:03 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            if (!TryCreateInstance(prefab, position, rotation, parent, worldPositionStays, out var instance))
C# でよく使用される構文なので、このままにしましょう。

2022-11-14 09:09 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +#pragma warning disable CC0120
ここの pragma は「switch 文を使うならすべてのケースを網羅して下さい」というものです。
pragma を外す方法は 3 つ考えられます。
どれが良いでしょうか？
1. すべてのケースを入れる。しかしそうするとどう頑張ってもコードカバレッジが 100% に達しません
2. .editorconfig ファイルからこの warning を切る。これは問題なく動作します
3. `if-then-else` でチェインさせる。これも問題なく動作します

2022-11-14 12:54 UTC, sus-taguchi-t commented on Runtime/Core/NgoClient.cs
> +#pragma warning disable IDE0016
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:54 UTC, sus-taguchi-t commented on Runtime/Core/NgoClient.cs
> +            if (networkTransportInitializer is null)
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:56 UTC, sus-taguchi-t commented on Runtime/Core/UnityTransportInitializer.cs
> +            if (networkTransport is UnityTransport unityTransport)
`NgoClient` で `NetworkTransport` の種類に応じたコンフィガーが呼ばれるので、

> NetworkTransportが処理対象か？

という判定は削除しました。

2022-11-14 12:56 UTC, sus-taguchi-t commented on Runtime/Core/ConnectionParameter.cs
> +    public class ConnectionParameter
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:57 UTC, sus-taguchi-t commented on Runtime/Core/IConnectionData.cs
> +    public interface IConnectionData
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:57 UTC, sus-taguchi-t commented on Runtime/Core/INgoServer.cs
> +        IObservable<ulong> OnClientConnected { get; }
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:57 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +        private Action<ConnectionApprovalRequest, ConnectionApprovalResponse> connectionApprovalCallback;
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:57 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +#pragma warning disable IDE0016
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:57 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +                throw new InvalidOperationException("Unable to reject client because the server is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:57 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +                    Logger.LogWarn($"Unable to reject client with client id {clientId} because it does not exist");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +        public bool RemoveClient(ulong clientId, string message)
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Core/NgoServer.cs
> +            if (clientIds.Except(networkManager.ConnectedClientsIds).Count() != 0)
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            => SpawnInternal(0, prefab, position, rotation, parent, worldPositionStays, SpawnType.ServerOwnership);
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn($"Null is accepted as {nameof(prefab)}");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 12:58 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn("GameObject without NetworkObject cannot be spawned");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:00 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            if (!TryCreateInstance(prefab, position, rotation, parent, worldPositionStays, out var instance))
修正しました。
例外を投げさせるよう変更したら bool 値を返させる必要性もなくなったので `out` パラメータも削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:00 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                Object.Destroy(instance);
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:00 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                Object.Destroy(instance);
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:00 UTC, sus-taguchi-t commented on Runtime/Spawning/INgoSpawnObserver.cs
> +        IObservable<NetworkObject[]> OnSpawnedAsObservable { get; }
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:01 UTC, sus-taguchi-t commented on Runtime/Spawning/INgoSpawnObserver.cs
> +
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:01 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:01 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnObserver.cs
> +    public class NgoSpawnObserver : INgoSpawnObserver
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-14 13:01 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnObserver.cs
> +            Clear();
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/0cf458ee2d91404b5f4fafe509411dbc5d6f0094

2022-11-15 04:49 UTC, sus-taguchi-t commented on Runtime/Core/UnityTransportInitializer.cs
> +            if (networkTransport is UnityTransport unityTransport)
`NgoClient` のコードで  `NetowrkTransport` の種類の取得方法が不適切だったので修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/04de24145b9a41ac47dc19ed117211442f9dc084

2022-11-15 04:49 UTC, sus-taguchi-t commented on Runtime/Spawning/NgoSpawnHelper.cs
> +#pragma warning disable CC0120
`3.` で対応しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/04de24145b9a41ac47dc19ed117211442f9dc084

2022-11-15 05:08 UTC, kiyohome commented on Runtime/Core/NgoClient.cs
> +#pragma warning disable IDE0016
LGTM

2022-11-15 05:15 UTC, kiyohome commented on Runtime/Core/NgoClient.cs
> +            if (networkTransportInitializer is null)
LGTM

2022-11-15 05:17 UTC, kiyohome commented on Runtime/Core/UnityTransportInitializer.cs
> +            if (networkTransport is UnityTransport unityTransport)
LGTM

2022-11-15 05:17 UTC, kiyohome commented on Runtime/Core/ConnectionParameter.cs
> +    public class ConnectionParameter
LGTM

2022-11-15 05:18 UTC, kiyohome commented on Runtime/Core/IConnectionData.cs
> +    public interface IConnectionData
LGTM

2022-11-15 05:18 UTC, kiyohome commented on Runtime/Spawning/INgoSpawnObserver.cs
> +        IObservable<NetworkObject[]> OnSpawnedAsObservable { get; }
LGTM

2022-11-15 05:18 UTC, kiyohome commented on Runtime/Spawning/INgoSpawnObserver.cs
> +
LGTM

2022-11-15 05:19 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
LGTM

2022-11-15 05:20 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnObserver.cs
> +    public class NgoSpawnObserver : INgoSpawnObserver
LGTM

2022-11-15 05:20 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnObserver.cs
> +            Clear();
LGTM

2022-11-15 14:39 UTC, kiyohome commented on Runtime/Core/INgoServer.cs
> +        IObservable<ulong> OnClientConnected { get; }
LGTM

2022-11-15 14:39 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +#pragma warning disable IDE0016
LGTM

2022-11-15 14:39 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +                    Logger.LogWarn($"Unable to reject client with client id {clientId} because it does not exist");
LGTM

2022-11-15 14:41 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +        public bool RemoveClient(ulong clientId, string message)
LGTM

2022-11-15 14:42 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +            if (clientIds.Except(networkManager.ConnectedClientsIds).Count() != 0)
LGTM

2022-11-15 14:42 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
LGTM

2022-11-15 14:42 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +    public static class NgoSpawnHelper
LGTM

2022-11-15 14:42 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            => SpawnInternal(0, prefab, position, rotation, parent, worldPositionStays, SpawnType.ServerOwnership);
LGTM

2022-11-15 14:42 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn($"Null is accepted as {nameof(prefab)}");
LGTM

2022-11-15 14:43 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                    Logger.LogWarn("GameObject without NetworkObject cannot be spawned");
LGTM

2022-11-15 14:43 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +#pragma warning disable CC0120
LGTM

2022-11-15 14:43 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +            if (!TryCreateInstance(prefab, position, rotation, parent, worldPositionStays, out var instance))
LGTM

2022-11-15 14:43 UTC, kiyohome commented on Runtime/Spawning/NgoSpawnHelper.cs
> +                Object.Destroy(instance);
LGTM

2022-11-15 14:44 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +                throw new InvalidOperationException("Unable to reject client because the server is not running");
LGTM

2022-11-15 14:44 UTC, kiyohome commented on Runtime/Core/NgoServer.cs
> +        private Action<ConnectionApprovalRequest, ConnectionApprovalResponse> connectionApprovalCallback;
LGTM

2022-11-15 16:32 UTC, kiyohome requested changes

2022-11-15 16:32 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +    public class ConnectionConfig
NgoClientやNgoServerと名前を合わせてNgoConfigがいいように思いました。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +        public string Key { get; internal set; }
Keyはどこでも使ってなさそうです。必要ですか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +        public static ConnectionConfig Default { get; } = new ConnectionConfig();
このデフォルトは必要でしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +        public void UpdateConfig
これはどんな使い方を想定していますか？
これは必要でしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
私がミスリードしたと思うのですが`Configer`はあまり単語として出てこないですね。
INetworkTransportEditorとかでどうでしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +        Type GetTargetType { get; }
プロパティは動詞のGetを付けるものでしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +        void SetConfig(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
INetworkTransportEditorに合わせて
`Edit(NetworkTransport networkTransport, ConnectionConfig connectionConfig)`
はいかがでしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/INgoClient.cs
> +    /// Interface for the mock to be used as NgoClient when testing.
アプリのテストでモックを使いそうでしょうか？
NetworkObjectが絡んでくるので難しくないでしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/INgoClient.cs
> +        bool IsRunning { get; }
IsRunningとIsConnectedの使い分けはどんな感じでしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/INgoClient.cs
> +        void SetNetworkTransportConfiger(INetworkTransportConfiger networkTransportConfiger);
SetとありますがAddではないですかね？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
ユーザーのネットワークが一時的に切れた場合とか、タイミングによってはこの例外が発生しそうな気がしました。
shutdownしているかどうか判定してshutdonwしていたらデバッグログを出してリターンでよいかと思いました。
OnNextの呼び出しも必要ですね。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
boolを返した方がいいかもですね。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
ここも通常利用で起きないでしょうか？
デバッグログ出してboolを返すとか。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to register named message handler because this client is not running");
ここも同じです。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to unregister named message handler because this client is not running");
ここも同じです。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoClient.cs
> +        #region Callbacks
`#region Callbacks`は何か意味があるのでしょうか？

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
タイミングによっては起こりそうなのでデバッグでいいように思いました。

2022-11-15 16:32 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
これもタイミングによって起きることであればデバッグでいいように思いました。

2022-11-16 00:15 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +    public class ConnectionConfig
良いと思います。
変更します。

2022-11-16 00:17 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public string Key { get; internal set; }
将来 `NetworkTransport` の種類が増えてそこで使用していたときに対応しやすいように入っているのかなと考えていました。
ただ現状まったく使用していないので削除しましょう。

2022-11-16 00:18 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public static ConnectionConfig Default { get; } = new ConnectionConfig();
デフォルトで使用するときは同じインスタンスを参照した方がメモリ削減になるかと思いました。
ただこれも冗長な気がするので削除します。

2022-11-16 00:23 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public void UpdateConfig
以下のような使い方を考えています。
- ロビーに戻って違うサーバに接続する際に `Address` `Port` のみを変更する
- サーバごとに `ConnectionData` や `TimeoutSeconds` を変えたい場合に値を変更する
毎回新しいインスタンスを作成させるような仕様にするのであれば不要だと思っています。

2022-11-16 00:23 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
良いと思います。
変更します。

2022-11-16 00:24 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        Type GetTargetType { get; }
付けないと思います。
削除します。

2022-11-16 00:24 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        void SetConfig(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
良いと思います。
変更します。

2022-11-16 00:30 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +    /// Interface for the mock to be used as NgoClient when testing.
使うことはできると思います。
`NetworkObject` は `NetworkManager` が動作していなくてもエラーを吐きません。
なので接続は成功しているかのように見せ、プレイヤー視点での動作等のテストのためにモックを使用することはできます。

2022-11-16 00:42 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +        bool IsRunning { get; }
確かネットワーク不良でサーバとの接続が切れている間も `IsRunning` は `true` であった記憶があります。
`NetworkManager` が `StartClient` を走らせると `IsRunning` は `true` になります。
`NetworkManager` がサーバに接続すると `IsConnected` は `true` になります。

2022-11-16 00:43 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +        void SetNetworkTransportConfiger(INetworkTransportConfiger networkTransportConfiger);
Add です。
修正します。

2022-11-16 00:47 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
実質的に `shutdown` しているかを表すのが `IsRunning` です。
なので通常運用していた場合は絶対に起こらない現象だと思います。

2022-11-16 00:47 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
これは通常利用でも起きます。
修正します。

2022-11-16 00:48 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to register named message handler because this client is not running");
修正します。

2022-11-16 00:48 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to unregister named message handler because this client is not running");
修正します。

2022-11-16 00:49 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        #region Callbacks
スコープ分けが一目で分かりやすい、かつ、一般的なテキストエディタを使用していれば `#region` `#endregion` 間は畳めます。

2022-11-16 00:50 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
良いと思います。
変更します。

2022-11-16 00:50 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
良いと思います。
変更します。

2022-11-16 01:34 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public void UpdateConfig
接続情報は外部から持ってきて新しくインスタンスを生成すると思うので、`Update` は削除します。

2022-11-16 01:41 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +    /// Interface for the mock to be used as NgoClient when testing.
テストはローカルでサーバを立ててやると思うのでインターフェースは削除します。

2022-11-16 02:03 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        #region Callbacks
冗長なので削除します。

2022-11-16 02:20 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/NgoServerTestSubSecond.cs
> +    public class NgoServerTestSubSecond
これをなくして NgoServerTestSub を一度動かせばテストがすべて通るように変更する。

2022-11-16 02:20 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +        bool IsRunning { get; }
公開 API として見せる必要はないので private にします。

2022-11-16 02:21 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
全体的に `try-catch` にして `bool` を返させるように変更します。

2022-11-16 02:21 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
全体的に `try-catch` にして `bool` を返させるように変更します。

2022-11-16 02:21 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to register named message handler because this client is not running");
全体的に `try-catch` にして `bool` を返させるように変更します。

2022-11-16 02:21 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to unregister named message handler because this client is not running");
全体的に `try-catch` にして `bool` を返させるように変更します。

2022-11-16 06:34 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
良いと思ったのですが、`Editor` サフィックスはエディター拡張スクリプトと混同してしまうので良くないかもしれないです。
造語であると開き直って `Configer` を使用するか、ないしは `Configurer` が一番無難な気がします。

2022-11-17 03:12 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +    public class ConnectionConfig
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:13 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public string Key { get; internal set; }
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:13 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public static ConnectionConfig Default { get; } = new ConnectionConfig();
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:13 UTC, sus-taguchi-t commented on Runtime/ConnectionConfig.cs
> +        public void UpdateConfig
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:15 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
`Helper` サフィックスも静的クラスに使うイメージが一般にあるのでやめます。
`IConnectionSetter` でいきましょう。

2022-11-17 03:15 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/d73f1147ceb87ee1a17cf301105d02364bb3b9b5

2022-11-17 03:15 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        Type GetTargetType { get; }
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:16 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        void SetConfig(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
インターフェース名を `IConnectionSetter` にするので `Set` にしましょう。

2022-11-17 03:16 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        void SetConfig(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/d73f1147ceb87ee1a17cf301105d02364bb3b9b5

2022-11-17 03:16 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +    /// Interface for the mock to be used as NgoClient when testing.
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:16 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +        bool IsRunning { get; }
`NetworkManager` のプロパティを直接見にいけば良いのでフィールド自体を削除します。

2022-11-17 03:17 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +        bool IsRunning { get; }
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:17 UTC, sus-taguchi-t commented on Runtime/INgoClient.cs
> +        void SetNetworkTransportConfiger(INetworkTransportConfiger networkTransportConfiger);
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:17 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:17 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
NGO をそのまま使用する形に寄せるので引数の入力チェック以外は NGO に任せます。

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
NGO をそのまま使用する形に寄せるので引数の入力チェック以外は NGO に任せます。

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to register named message handler because this client is not running");
NGO をそのまま使用する形に寄せるので引数の入力チェック以外は NGO に任せます。

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to register named message handler because this client is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to unregister named message handler because this client is not running");
NGO をそのまま使用する形に寄せるので引数の入力チェック以外は NGO に任せます。

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to unregister named message handler because this client is not running");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:19 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        #region Callbacks
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:20 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:20 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:20 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/NgoServerTestSubSecond.cs
> +    public class NgoServerTestSubSecond
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cfdb5b9a35abc6ee17542cc0929b79716e86de51

2022-11-17 03:55 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +    public class ConnectionConfig
LGTM

2022-11-17 03:56 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +        public string Key { get; internal set; }
LGTM

2022-11-17 03:56 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +        public static ConnectionConfig Default { get; } = new ConnectionConfig();
LGTM

2022-11-17 03:57 UTC, kiyohome commented on Runtime/ConnectionConfig.cs
> +        public void UpdateConfig
LGTM

2022-11-17 03:58 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
ファイル名が直ってない？

2022-11-17 04:53 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
すみません。
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/f71aa9988db5cd4e27db632d19c80500151cbcee

2022-11-17 05:17 UTC, kiyohome requested changes

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoClient.cs
> +        /// Sets NetworkTransportConfiger.
`configer`が3か所残ってますね。

2022-11-17 05:17 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +        void Set(NetworkTransport networkTransport, NgoConfig connectionConfig);
できるだけタイプと変数名`connectionConfig`を合わせた方がよくないでしょうか？
全体的に変更前のタイプ名となってます。

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoClient.cs
> +            if (networkManager.IsClient || networkManager.IsServer || networkManager.IsHost)
`networkManager.IsServer || networkManager.IsHost`は必要なのでしょうか？

NgoClientを使う時はSeverにはならないと思ってました。
Hostも提供してないという話なのでいらないのでは？と思いました。

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public IReadOnlyDictionary<ulong, NetworkClient> ConnectedClients
コレクションはnullでなく空を返した方がよくないでしょうか？

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                throw new InvalidOperationException("Unable to stop server because it is not running");
サーバーの停止は止める時だと思うので例外が出ない方がいいと思いました。
本番稼働だとやり方はまだ分かってませんが例外が出ると通知が走りオペレータに連絡がいくこともあるので。

IsServer=falseでShutdownで例外出なければこのチェック無くてもよいように思いました。

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoServer.cs
> +            if (networkManager.NetworkConfig.ConnectionApproval)
`NetworkConfig.ConnectionApproval`に関係なく設定した方がいいのではないでしょうか？

`NetworkConfig.ConnectionApproval`の使い方ですがテストなどで一時的に外して実行とかあると思います。
`NetworkConfig.ConnectionApproval`に関係なく設定しておいて、`NetworkConfig.ConnectionApproval`がfalseの場合はデバッグログ（falseだけど設定してるよ、trueにしないと動かないよ）を出す、でいかがでしょうか？

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
修正されてないようです。
→修正済みを確認しました！

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
こちらも修正されてない？
→修正済みを確認しました！

2022-11-17 05:17 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public GameObject SpawnWithServerOwnership
こちらはIsServerのチェック不要ですかね？

2022-11-17 05:19 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +    public interface INetworkTransportConfiger
LGTM

2022-11-17 05:19 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +        Type GetTargetType { get; }
LGTM

2022-11-17 05:20 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +        void SetConfig(NetworkTransport networkTransport, ConnectionConfig connectionConfig);
LGTM

2022-11-17 05:20 UTC, kiyohome commented on Runtime/INgoClient.cs
> +    /// Interface for the mock to be used as NgoClient when testing.
LGTM

2022-11-17 05:20 UTC, kiyohome commented on Runtime/INgoClient.cs
> +        bool IsRunning { get; }
LGTM

2022-11-17 05:21 UTC, kiyohome commented on Runtime/INgoClient.cs
> +        void SetNetworkTransportConfiger(INetworkTransportConfiger networkTransportConfiger);
LGTM

2022-11-17 05:21 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to disconnect because this client is not running");
LGTM

2022-11-17 05:21 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to send message to server because this client is not running");
LGTM

2022-11-17 05:21 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to register named message handler because this client is not running");
LGTM

2022-11-17 05:21 UTC, kiyohome commented on Runtime/NgoClient.cs
> +                throw new InvalidOperationException("Unable to unregister named message handler because this client is not running");
LGTM

2022-11-17 05:21 UTC, kiyohome commented on Runtime/NgoClient.cs
> +        #region Callbacks
LGTM

2022-11-17 07:35 UTC, kiyohome requested changes

2022-11-17 07:35 UTC, kiyohome commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
タイムアウトでテストが落ちます。
`[UnityTest]`だと並行でテスト実行が走るんですかね？

タイムアウトのテスト以外のところは定数を定義して一律で長いタイムアウト180秒とかを設定して欲しいです。

2022-11-17 07:35 UTC, kiyohome commented on Tests/Runtime/Sub/ClientMessagingHub.cs
> +    public class ClientMessagingHub : IDisposable
MessagingHubというクラスが2つあるんですが、ソース理解が難しいですね。
ひょっとしたらクラス名の問題かもしれないですが、MessagingHubというと異なるアプリを紐づけるようなイメージがあって、その意識で見るとよく分からないですね。
このクラスの役割を今度教えてください。

2022-11-17 08:01 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        /// Sets NetworkTransportConfiger.
すみません。
削除します。

2022-11-17 08:01 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        void Set(NetworkTransport networkTransport, NgoConfig connectionConfig);
すみません。
修正します。

2022-11-17 08:02 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            if (networkManager.IsClient || networkManager.IsServer || networkManager.IsHost)
分かりました。
なくします。

2022-11-17 08:05 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +        public IReadOnlyDictionary<ulong, NetworkClient> ConnectedClients
つまり条件が `false` で呼ばれたときは毎回新しいディクショナリを `new` するという認識でよろしいでしょうか？

2022-11-17 08:06 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                throw new InvalidOperationException("Unable to stop server because it is not running");
分かりました。
`shutdown` で例外は出ないので素通りさせます。

2022-11-17 08:12 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +            if (networkManager.NetworkConfig.ConnectionApproval)
分かりました。
しかし `NetworkManager.NetworkConfig.ConnectionApproval == false` のときに `NetworkManager.ConnectionApprovalCallback` を設定すると `NetworkManager` の中で warning ログが出てしまうので、このときは設定はせずにデバッグログを出すようにします。

2022-11-17 08:16 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
すみません。
修正します。

2022-11-17 08:16 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
すみません。
修正します。

2022-11-17 08:37 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +        public GameObject SpawnWithServerOwnership
必要です。
修正します。

2022-11-17 09:04 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
おそらく処理速度の問題で、メインのテストが切り替わる前にサブのテストが動作してしまっているのが原因と思われます。
なのでサブの待機時間を増やします。

2022-11-17 09:05 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/ClientMessagingHub.cs
> +    public class ClientMessagingHub : IDisposable
分かりました。

2022-11-18 00:15 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        }
`NetworkManager.IsClient == false` の場合は 222 行目の `CustomMessagingManager` が null になる関係上 `NullReferenceException` が投げられます。
なのでこのチェックだけはあった方が使いやすいかなと思いました。
`RegisterMessageHandler` と `UnregisterMessageHandler` も同様です。

2022-11-18 01:26 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +        public IReadOnlyDictionary<ulong, NetworkClient> ConnectedClients
空のディクショナリを `private` で持っておいてそれを返す。

2022-11-18 01:45 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/ClientMessagingHub.cs
> +    public class ClientMessagingHub : IDisposable
`MessagingManager` という名称に変更します。

2022-11-18 02:14 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        }
`private` メソッドで `NetworkManager.IsClient` をチェックしてエラーハンドリングさせます。

2022-11-18 02:32 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +            if (networkManager.NetworkConfig.ConnectionApproval)
`NetworkManager` のログを出させる形にするので条件判定はすべて除いてただセットするだけにします。

2022-11-18 03:20 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        }
サーバ側でも同じように処理します。

2022-11-18 03:27 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:27 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:27 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        /// Sets NetworkTransportConfiger.
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:27 UTC, sus-taguchi-t commented on Runtime/INetworkTransportConfiger.cs
> +        void Set(NetworkTransport networkTransport, NgoConfig connectionConfig);
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +            if (networkManager.IsClient || networkManager.IsServer || networkManager.IsHost)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +        public IReadOnlyDictionary<ulong, NetworkClient> ConnectedClients
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                throw new InvalidOperationException("Unable to stop server because it is not running");
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +            if (networkManager.NetworkConfig.ConnectionApproval)
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +        public GameObject SpawnWithServerOwnership
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/ClientMessagingHub.cs
> +    public class ClientMessagingHub : IDisposable
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 03:28 UTC, sus-taguchi-t commented on Runtime/NgoClient.cs
> +        }
修正しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/cf93f29223073b9c02e027238a2f0f9bdfc3322c

2022-11-18 04:26 UTC, kiyohome requested changes

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                this.networkManager.ConnectionApprovalCallback = (_, response) => response.Approved = true;
ConnectionApprovalのデフォルトがtrueでConnectionApprovalCallbackを設定しないと動かないとかでしょうか？
もしデフォルトで入れておかないと動かないのならConnectionApprovalをチェックせずに設定した方がよくないでしょうか？

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                    Logger.LogWarn($"Unable to remove client with client id {clientId} because it does not exist");
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                Logger.LogWarn($"{nameof(clientIds)} contains some ids that does not exist: "
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Tests/Runtime/Sub/NgoServerTestSubSecond.cs
> +    public class NgoServerTestSubSecond
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoClient.cs
> +        /// Sets NetworkTransportConfiger.
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/INetworkTransportConfiger.cs
> +        void Set(NetworkTransport networkTransport, NgoConfig connectionConfig);
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoClient.cs
> +            if (networkManager.IsClient || networkManager.IsServer || networkManager.IsHost)
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public IReadOnlyDictionary<ulong, NetworkClient> ConnectedClients
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                throw new InvalidOperationException("Unable to stop server because it is not running");
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +            if (networkManager.NetworkConfig.ConnectionApproval)
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public GameObject SpawnWithServerOwnership
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
落ちますね、3回ぐらいやってみましたがSubのテスト実行で落ちますね。

2022-11-18 04:26 UTC, kiyohome commented on Tests/Runtime/Sub/ClientMessagingHub.cs
> +    public class ClientMessagingHub : IDisposable
LGTM

2022-11-18 04:26 UTC, kiyohome commented on Runtime/NgoClient.cs
> +        }
LGTM

2022-11-18 04:50 UTC, kiyohome requested changes

2022-11-18 04:50 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public async UniTask StartServerAsync(CancellationToken token = default)
サーバーがスタートしたよ、とデバッグログが欲しいです。

2022-11-18 04:50 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public async UniTask StartServerAsync(CancellationToken token = default)
クライアントも接続できたよ、とデバッグログが欲しいです。

2022-11-18 04:52 UTC, kiyohome commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
毎回ここで落ちてるみたいです。
```
StartServerWithConnectionApprovalSub (2.418s)
---
Expected: True
  But was:  False
---
at Extreal.Integration.Multiplay.NGO.Test.Sub.NgoServerTestSub.<StartServerWithConnectionApprovalSub>b__9_0 () [0x001e8] in C:\Users\kiyoh\work\xr\Extreal.Dev_clone_0\Packages\Extreal.Integration.Multiplay.NGO\Tests\Runtime\Sub\NgoServerTestSub.cs:85
```

2022-11-18 05:07 UTC, sus-taguchi-t commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
さらに待機時間を増やしてみました。
これでもまだ落ちるようであればどのように落ちているか見せていただけると嬉しいです。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/17523ac5f58b2681ae65e9e5485bfac3d18cfc49

2022-11-18 05:11 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                this.networkManager.ConnectionApprovalCallback = (_, response) => response.Approved = true;
その通りだと思います。
ここの記述は削除します。

【補足】
`ConnectionApproval == true` で `ConnectionApprovalChack` に何もコールバックを指定していない場合はサーバはすべてのクライアントからの接続を拒否します。
しかしこれは NGO の仕様でありアプリ作成者側の実装不備（`ConnectionApproval == true` で設定するのであれば何かしらのコールバックは指定すべき）なので記述を削除して問題ないです。

2022-11-18 05:11 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +                this.networkManager.ConnectionApprovalCallback = (_, response) => response.Approved = true;
修正しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/17523ac5f58b2681ae65e9e5485bfac3d18cfc49

2022-11-18 05:13 UTC, sus-taguchi-t commented on Runtime/NgoServer.cs
> +        public async UniTask StartServerAsync(CancellationToken token = default)
コールバックの方で実装してあります。

2022-11-18 05:16 UTC, kiyohome commented on Runtime/NgoServer.cs
> +                this.networkManager.ConnectionApprovalCallback = (_, response) => response.Approved = true;
LGTM

2022-11-18 05:29 UTC, kiyohome commented on Runtime/NgoServer.cs
> +        public async UniTask StartServerAsync(CancellationToken token = default)
あっinfo？debug？のボタンがOFFになってるだけでした。すみません。

2022-11-18 05:41 UTC, kiyohome commented on Tests/Runtime/Sub/NgoServerTestSub.cs
> +            _ = await ngoClient.ConnectAsync(connectionConfig);
通りました！

2022-11-18 05:46 UTC, sus-taguchi-t commented on Runtime/Extreal.Integration.Multiplay.NGO.asmdef
> +        "Extreal.Framework.Analyzer"
削除しました！
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/2/commits/58424ceef8a7fe2b32c6aad3fe4fc54b20c83fe7

2022-11-18 06:03 UTC, kiyohome commented on Runtime/Extreal.Integration.Multiplay.NGO.asmdef
> +        "Extreal.Framework.Analyzer"
LGTM

2022-11-18 06:04 UTC, kiyohome approved these changes

2022-11-18 06:04 UTC, merged