NGOのサンプルを追加する
extreal-dev/Extreal.Integration.Multiplay pull request #3
Opened 2022-11-23 13:12 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- NGOのサンプルを追加しました。
- 素のNGO、Extrealを使った場合のサンプル2つです。

# What did you verify? (何を確認しましたか?)

サンプルのため下記はチェックしていないです。

- [ ] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [ ] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [ ] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [ ] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [ ] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

- [ ] Extrealのサンプルは想定するアーキテクチャを意識してます。改善点はありますか？

2022-11-24 05:58 UTC, kiyohome commented on Samples~/MVS2/App/SceneName.cs
> +﻿namespace Extreal.Integration.Multiplay.NGO.MVS.App
不要なのでディレクトリごと消す。

2022-11-24 07:06 UTC, sus-taguchi-t requested changes

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/MVS/Common/NetworkThirdPersonController.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
このプリプロセッサは必要でしょうか？
このサンプル自体が `InputSystem` の使用を前提としているため不要な気がします。
他の 4 箇所についても同様です。

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/MVS/Common/StarterAssets/InputSystem/StarterAssetsInputs.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
こちらも `InputSystem` の使用は前提なので不要な気がします。
もう 1 箇所あります。

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/MVS/Common/StarterAssets/Mobile/Scripts/Utilities/MobileDisableAutoSwitchControls.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
こちらも不要な気がします。

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/MVS/Common/StarterAssets/Mobile/Scripts/Utilities/MobileDisableAutoSwitchControls.cs
> +#if ENABLE_INPUT_SYSTEM && (UNITY_IOS || UNITY_ANDROID) && STARTER_ASSETS_PACKAGES_CHECKED
ここは `UNITY_IOS || UNITY_ANDROID` だけ残せばよいと思います。

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/MVS/README.md
> +  - Symbol: STARTER_ASSETS_PACKAGES_CHECKED
スクリプトからシンボルを取り除いた場合、ここは不要になります。

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/MVS/README.md
> +- Install this sample from Package Manager.
NGO の README に書くのでここは削除で良いと思います。

2022-11-24 07:06 UTC, sus-taguchi-t commented on Samples~/NGO/App/AppInitializer.cs
> +﻿using Extreal.Core.Logging;
このサンプルは何のためにあるのでしょうか？
公開するのであれば `package.json` に設定して、かつ、Assembly Definition の名前や名前空間も変更した方がいいかなと思いました。
逆に公開しないのであればこれの存在理由の説明がどこかに欲しいと思いました。

2022-11-24 07:30 UTC, kiyohome commented on Samples~/MVS2/App/SceneName.cs
> +﻿namespace Extreal.Integration.Multiplay.NGO.MVS.App
削除しました
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/3/commits/524920fd31e197f318a1d22ab44ce9a239e3f3ab

2022-11-24 07:45 UTC, kiyohome commented on Samples~/MVS/Common/NetworkThirdPersonController.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
元のソースをあまり変更したくなかったのですがスナップショットという扱いであれば変更しても大丈夫そうですね。
2つのシンボル（ENABLE_INPUT_SYSTEM、STARTER_ASSETS_PACKAGES_CHECKED）を削除します。

2022-11-24 08:12 UTC, kiyohome commented on Samples~/MVS/Common/NetworkThirdPersonController.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
2つのシンボルを削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/3/commits/b67974d4157996bb4977705dbb68cdc2d55d48db

2022-11-24 08:13 UTC, kiyohome commented on Samples~/MVS/Common/StarterAssets/InputSystem/StarterAssetsInputs.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
2つのシンボルを削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/commit/b67974d4157996bb4977705dbb68cdc2d55d48db

2022-11-24 08:13 UTC, kiyohome commented on Samples~/MVS/Common/StarterAssets/Mobile/Scripts/Utilities/MobileDisableAutoSwitchControls.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
2つのシンボルを削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/commit/b67974d4157996bb4977705dbb68cdc2d55d48db

2022-11-24 08:13 UTC, kiyohome commented on Samples~/MVS/Common/StarterAssets/Mobile/Scripts/Utilities/MobileDisableAutoSwitchControls.cs
> +#if ENABLE_INPUT_SYSTEM && (UNITY_IOS || UNITY_ANDROID) && STARTER_ASSETS_PACKAGES_CHECKED
2つのシンボルを削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/commit/b67974d4157996bb4977705dbb68cdc2d55d48db

2022-11-24 08:13 UTC, kiyohome commented on Samples~/MVS/README.md
> +  - Symbol: STARTER_ASSETS_PACKAGES_CHECKED
手順を削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/commit/b67974d4157996bb4977705dbb68cdc2d55d48db

2022-11-24 08:20 UTC, kiyohome commented on Samples~/MVS/README.md
> +- Install this sample from Package Manager.
リポジトリ直下のREADMEに内容を移動してこのファイルを削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/3/commits/50043a819d15c297fe6a452a6dd96bfde7e01894

2022-11-24 08:22 UTC, kiyohome commented on Samples~/NGO/App/AppInitializer.cs
> +﻿using Extreal.Core.Logging;
素のNGOサンプルを内部的に持っていてもよいかと思いましたがノイズになるので削除しました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/3/commits/a8ed360c06ef2e691907a9b55ebc734bc2cd1fa4

2022-11-24 09:06 UTC, kiyohome commented
- [ ] NGOのSample：StageNameはXxxxStageという名前に変更する。シーン名と重複するため。
- [ ] NGOのSample：VContainerのインジェクションを推奨のコンストラクタにする。
- [ ] NGOのサンプル：RuntimeInitializeOnLoadMethodをやめてエントリポイントでやる。追いやすくなる。
- [ ] 
上記の対応も入れました。
https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/3/commits/553d87fe2ea9e8cacf45a26461936346d089b69b

2022-11-25 06:13 UTC, sus-taguchi-t commented on Samples~/MVS2/App/SceneName.cs
> +﻿namespace Extreal.Integration.Multiplay.NGO.MVS.App
確認しました！

2022-11-25 06:14 UTC, sus-taguchi-t commented on Samples~/MVS/Common/NetworkThirdPersonController.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
確認しました！

2022-11-25 06:15 UTC, sus-taguchi-t commented on Samples~/MVS/Common/StarterAssets/InputSystem/StarterAssetsInputs.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
確認しました！

2022-11-25 06:17 UTC, sus-taguchi-t commented on Samples~/MVS/Common/StarterAssets/Mobile/Scripts/Utilities/MobileDisableAutoSwitchControls.cs
> +#if ENABLE_INPUT_SYSTEM && STARTER_ASSETS_PACKAGES_CHECKED
確認しました！

2022-11-25 06:17 UTC, sus-taguchi-t commented on Samples~/MVS/Common/StarterAssets/Mobile/Scripts/Utilities/MobileDisableAutoSwitchControls.cs
> +#if ENABLE_INPUT_SYSTEM && (UNITY_IOS || UNITY_ANDROID) && STARTER_ASSETS_PACKAGES_CHECKED
確認しました！

2022-11-25 06:20 UTC, sus-taguchi-t commented on Samples~/MVS/README.md
> +  - Symbol: STARTER_ASSETS_PACKAGES_CHECKED
確認しました！

2022-11-25 06:22 UTC, sus-taguchi-t commented on Samples~/MVS/README.md
> +- Install this sample from Package Manager.
確認しました！

2022-11-25 06:22 UTC, sus-taguchi-t commented on Samples~/NGO/App/AppInitializer.cs
> +﻿using Extreal.Core.Logging;
確認しました！

2022-11-25 06:27 UTC, sus-taguchi-t approved these changes

2022-11-25 06:28 UTC, merged